modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/BaKYCoder/BackToBed/issues"

[[mods]]
   modId="backtobed"
   version="${version}"
   displayName="BackToBed"
   displayURL="https://www.curseforge.com/minecraft/mc-mods/back-to-bed"
   logoFile="logo.png"
   authors="BaKY"
   description='''
   This mod adds a handy return device, permitting you to relocate to the spawn point with ease.
   '''

[[dependencies.backtobed]]
   modId="forge"
   mandatory=true
   versionRange="[41,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.backtobed]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19,1.19.3)"
   ordering="NONE"
   side="BOTH"
