modLoader="javafml"
loaderVersion="[44,)"
license="MIT License"

[[mods]]
    modId="backtobed"
    version="1.0.0"
    displayName="Back To Bed"
        logoFile="backtobed_logo.png"
        authors="BaKY"
        description="Enjoy the convenience of effortless homeward travels."

[[dependencies.backtobed]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.backtobed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
